/*
 * Dig Airdrop
 *
 * This is the dfy airdrop tool.  It eats JSON arrays with three strings and after verifying the signature on the dig address, 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Digger struct {

	Ethaddr string `json:"ethaddr,omitempty"`

	Digaddr string `json:"digaddr,omitempty"`

	Signature string `json:"signature,omitempty"`
}
